spring:
  application:
    name: UserManagementSystem
  datasource:
    url: jdbc:mysql://database:3306/mydb
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
