name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

jobs:
  build-test:
    name: Build, test backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run tests
        working-directory: backend
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build --no-cache backend-run

      - name: Save image
        run: docker save -o backend-run.tar backend-run

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: backend-run.tar
          path: backend-run.tar
