name: Frontend CI/CD

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

jobs:
  build-test-lint:
    name: Build, test, lint Angular frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Clean install dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint code
        working-directory: frontend
        run: npm run lint

      - name: Run tests
        working-directory: frontend
        run: npm test -- --watch=false --no-progress --browsers=ChromeHeadless

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-test-lint
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose --profile deploy build --no-cache frontend-run

      - name: Save image
        run: docker save -o frontend-run.tar frontend-run
      
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: frontend-run.tar
          path: frontend-run.tar
